/* TRIGGER VENDAS ESTORNADAS*/

DELIMITER $

CREATE TRIGGER TRIGGER_VENDAS_ESTORNADA AFTER DELETE
ON VENDAS
FOR EACH ROW
BEGIN
 
	UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL - OLD.VALOR
	WHERE DATA_TRANSACAO < OLD.DATA_TRANSACAO;
    
END $


